title: Tech for Teaching
description: Articles on using computers and Internet technology to prepare materials for your course
author_name: David Chappell
author_photo: /assets/images/author.jpg
author_blurb: >
    A computer programmer with 25 years of experience using and creating web technology.
    He enjoys applying his skills to the creation of language-teaching materials. 
google_analytics: UA-48777822-8 
google_ad_client: ca-pub-9697496962185999
google_ad_slot: 4238015419
defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/images/title/image.png
      image_alt: Students listen intently as an instructor jestures toward a screen showing a laptop computer, camera, and microphone.
