title: Tech for Teaching
description: Articles on using computers and Internet technology to prepare materials for your course
author_blurb: The author is a computer programmer who has been creating software using Web technologies for 25 years. On this site he shares what he learned applying his experience to the creation of teaching aids.
google_analytics: UA-48777822-8 
